"""Add filesize column

Revision ID: 199583d30108
Revises: c8ee504f0390
Create Date: 2024-03-14 15:23:37.333774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '199583d30108'
down_revision: Union[str, None] = 'c8ee504f0390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('size', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'size')
    # ### end Alembic commands ###
