"""Initialize

Revision ID: be910f2b8ba5
Revises: 
Create Date: 2024-03-07 15:35:33.640997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be910f2b8ba5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('GREEN', 'WARNED', 'BANNED', 'DORMANT', name='userstatus', native_enum=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender', native_enum=False), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('billing_name', sa.String(), nullable=False),
    sa.Column('password_reset_token', sa.String(), nullable=True),
    sa.Column('terms_and_conditions_agreement', sa.DateTime(), nullable=False),
    sa.Column('marketing_promotions_agreement', sa.DateTime(), nullable=True),
    sa.Column('remark', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('authentication_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authentication_logs')
    op.drop_table('users')
    # ### end Alembic commands ###
