"""Remove size, Adding filename

Revision ID: f86ca439f38e
Revises: 80b6f43fede3
Create Date: 2024-03-15 21:36:37.928623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f86ca439f38e'
down_revision: Union[str, None] = '80b6f43fede3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('filename', sa.String(), nullable=False))
    op.drop_column('files', 'size')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('files', 'filename')
    # ### end Alembic commands ###
